version = 0.1

[default.deploy.parameters]
stack_name = "ws-serverless-patterns-userprofile"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-userprofile"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserPoolId=\"us-east-1_L5Ic03fPy\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
